export const SHOW_INVENTORY_DIALOG="SHOW_INVENTORY_DIALOG";
export const SHOW_STOCKCARD_DIALOG="SHOW_STOCKCARD_DIALOG";

export const SET_SELECTED_INVENTORY_ITEM="SET_SELECTED_INVENTORY_ITEM";

export const CHECK_HAS_REF_ERROR_REQUEST="CHECK_HAS_REF_ERROR_REQUEST";
export const CHECK_HAS_REF_ERROR_SUCCESS="CHECK_HAS_REF_ERROR_SUCCESS";
export const CHECK_HAS_REF_ERROR_FAILURE="CHECK_HAS_REF_ERROR_FAILURE";

export const FETCH_INVENTORY_REQUEST="FETCH_INVENTORY_REQUEST";
export const FETCH_INVENTORY_SUCCESS="FETCH_INVENTORY_SUCCESS";
export const FETCH_INVENTORY_FAILURE="FETCH_INVENTORY_FAILURE";

export const FETCH_STOCKCARD_REQUEST="FETCH_STOCKCARD_REQUEST";
export const FETCH_STOCKCARD_SUCCESS="FETCH_STOCKCARD_SUCCESS";
export const FETCH_STOCKCARD_FAILURE="FETCH_STOCKCARD_FAILURE";

export const PUT_INVENTORY_REQUEST="PUT_INVENTORY_REQUEST";
export const PUT_INVENTORY_SUCCESS="PUT_INVENTORY_SUCCESS";
export const PUT_INVENTORY_FAILURE="PUT_INVENTORY_FAILURE";