export const SHOW_VEND_ORDER_DIALOG="SHOW_VEND_ORDER_DIALOG";

export const SELECTED_VEND_ORDER="SELECTED_VEND_ORDER";

export const FETCH_VEND_ORDER_REQUEST="FETCH_VEND_ORDER_REQUEST";
export const FETCH_VEND_ORDER_SUCCESS="FETCH_VEND_ORDER_SUCCESS";
export const FETCH_VEND_ORDER_FAILURE="FETCH_VEND_ORDER_FAILURE";

export const FETCH_GRN_ORDER_REQUEST="FETCH_GRN_ORDER_REQUEST";
export const FETCH_GRN_ORDER_SUCCESS="FETCH_GRN_ORDER_SUCCESS";
export const FETCH_GRN_ORDER_FAILURE="FETCH_GRN_ORDER_FAILURE";

export const PUSH_VEND_ORDER_REQUEST="PUSH_VEND_ORDER_REQUEST";
export const PUSH_VEND_ORDER_SUCCESS="PUSH_VEND_ORDER_SUCCESS";
export const PUSH_VEND_ORDER_FAILURE="PUSH_VEND_ORDER_FAILURE";

export const UPDATE_VEND_ORDER_REQUEST="UPDATE_VEND_ORDER_REQUEST";
export const UPDATE_VEND_ORDER_SUCCESS="UPDATE_VEND_ORDER_SUCCESS";
export const UPDATE_VEND_ORDER_FAILURE="UPDATE_VEND_ORDER_FAILURE";