export const SHOW_CUST_TXN_DIALOG="SHOW_CUST_TXN_DIALOG";

export const SELECTED_CUST_TXN="SELECTED_CUST_TXN";

export const FETCH_CUST_DEL_REQUEST="FETCH_CUST_DEL_REQUEST";
export const FETCH_CUST_DEL_SUCCESS="FETCH_CUST_DEL_SUCCESS";
export const FETCH_CUST_DEL_FAILURE="FETCH_CUST_DEL_FAILURE";

export const FETCH_CUST_DEL_RQ_REQUEST="FETCH_CUST_DEL_RQ_REQUEST";
export const FETCH_CUST_DEL_RQ_SUCCESS="FETCH_CUST_DEL_RQ_SUCCESS";
export const FETCH_CUST_DEL_RQ_FAILURE="FETCH_CUST_DEL_RQ_FAILURE";

export const PUSH_CUST_DEL_REQUEST="PUSH_CUST_DEL_REQUEST";
export const PUSH_CUST_DEL_SUCCESS="PUSH_CUST_DEL_SUCCESS";
export const PUSH_CUST_DEL_FAILURE="PUSH_CUST_DEL_FAILURE";

export const UPDATE_VEND_ORDER_REQUEST="UPDATE_VEND_ORDER_REQUEST";
export const UPDATE_VEND_ORDER_SUCCESS="UPDATE_VEND_ORDER_SUCCESS";
export const UPDATE_VEND_ORDER_FAILURE="UPDATE_VEND_ORDER_FAILURE";