export const SHOW_PARTNER_DIALOG="SHOW_PARTNER_DIALOG";
export const PARTNER_TYPE="PARTNER_TYPE";

export const SET_SELECTED_PARTNER_ITEM="SET_SELECTED_PARTNER_ITEM";

export const FETCH_PARTNER_REQUEST="FETCH_PARTNER_REQUEST";
export const FETCH_PARTNER_SUCCESS="FETCH_PARTNER_SUCCESS";
export const FETCH_PARTNER_FAILURE="FETCH_PARTNER_FAILURE";

export const PUT_PARTNER_REQUEST="PUT_PARTNER_REQUEST";
export const PUT_PARTNER_SUCCESS="PUT_PARTNER_SUCCESS";
export const PUT_PARTNER_FAILURE="PUT_PARTNER_FAILURE";