export const SHOW_WH_DIALOG="SHOW_WH_DIALOG";

export const FETCH_WHS_REQUEST="FETCH_WHS_REQUEST";
export const FETCH_WHS_SUCCESS="FETCH_WHS_SUCCESS";
export const FETCH_WHS_FAILURE="FETCH_WHS_FAILURE";

export const PUT_WHS_REQUEST="PUT_WHS_REQUEST";
export const PUT_WHS_SUCCESS="PUT_WHS_SUCCESS";
export const PUT_WHS_FAILURE="PUT_WHS_FAILURE";

export const CHECK_WH_EXIST_REQUEST="CHECK_WH_EXIST_REQUEST";
export const CHECK_WH_EXIST_SUCCESS="CHECK_WH_EXIST_SUCCESS";
export const CHECK_WH_EXIST_FAILURE="CHECK_WH_EXIST_FAILURE";