export const SHOW_UOM_DIALOG="SHOW_UOM_DIALOG";
export const SET_SELECTED_UOM_ITEM="SET_SELECTED_UOM_ITEM";

export const FETCH_UOM_REQUEST="FETCH_UOM_REQUEST";
export const FETCH_UOM_SUCCESS="FETCH_UOM_SUCCESS";
export const FETCH_UOM_FAILURE="FETCH_UOM_FAILURE";

export const PUT_UOM_REQUEST="PUT_UOM_REQUEST";
export const PUT_UOM_SUCCESS="PUT_UOM_SUCCESS";
export const PUT_UOM_FAILURE="PUT_UOM_FAILURE";