export const FETCH_USER_NOTIFICATIONS_REQUEST="FETCH_USER_NOTIFICATIONS_REQUEST";
export const FETCH_USER_NOTIFICATIONS_SUCCESS="FETCH_USER_NOTIFICATIONS_SUCCESS";
export const FETCH_USER_NOTIFICATIONS_ERROR="FETCH_USER_NOTIFICATIONS_ERROR";

export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR="USER_LOGIN_ERROR";