export const SHOW_TXN_DOC_DIALOG="SHOW_TXN_DOC_DIALOG";
export const TXN_DOC_TYPE="TXN_DOC_TYPE";

export const SET_SELECTED_TXN_DOC_ITEM="SET_SELECTED_TXN_DOC_ITEM";

export const FETCH_TXN_DOC_REQUEST="FETCH_TXN_DOC_REQUEST";
export const FETCH_TXN_DOC_SUCCESS="FETCH_TXN_DOC_SUCCESS";
export const FETCH_TXN_DOC_FAILURE="FETCH_TXN_DOC_FAILURE";

export const PUT_TXN_DOC_REQUEST="PUT_TXN_DOC_REQUEST";
export const PUT_TXN_DOC_SUCCESS="PUT_TXN_DOC_SUCCESS";
export const PUT_TXN_DOC_FAILURE="PUT_TXN_DOC_FAILURE";