export const SHOW_INV_GROUP_DIALOG="SHOW_INV_GROUP_DIALOG";

export const SET_SELECTED_INV_GROUP_ITEM="SET_SELECTED_INV_GROUP_ITEM";

export const FETCH_INV_GROUP_REQUEST="FETCH_INV_GROUP_REQUEST";
export const FETCH_INV_GROUP_SUCCESS="FETCH_INV_GROUP_SUCCESS";
export const FETCH_INV_GROUP_FAILURE="FETCH_INV_GROUP_FAILURE";

export const PUSH_INV_GROUP_REQUEST="PUSH_INV_GROUP_REQUEST";
export const PUSH_INV_GROUP_SUCCESS="PUSH_INV_GROUP_SUCCESS";
export const PUSH_INV_GROUP_FAILURE="PUSH_INV_GROUP_FAILURE";